name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: '5.0'

    - name: Install Dependencies
      run: |
        npm install
        npm install -g jest
    - run: npm test